#!/usr/bin/env ts-node
import 'dotenv/config'; 
import { writeFileSync } from 'fs'; 
import { createClient } from '@supabase/supabase-js';

const url = process.env.NEXT_PUBLIC_SUPABASE_URL || "https://kkazhcihooovsuwravhs.supabase.co";
const key = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtrYXpoY2lob29vdnN1d3JhdmhzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1MzMwMzUsImV4cCI6MjA2MjEwOTAzNX0.-HzjqXYqgThN0PrbrwZlm5GWK1vOGOeYHEEFrt0OpwM";

const supabase = createClient(url, key);

function toTable(tasks: any[]) { 
  const header = `| Tittel | Beskrivelse | Årstider | Boligtyper | Frekvens | Prioritet |
|---|---|---|---|---:|---|`;
  const rows = tasks.map(t => `| ${t.title} | ${String(t.description||'').replace(/\n/g,' ')} | ${t.seasons.join(', ')} | ${t.property_types.join(', ')} | ${t.frequency_months} mnd | ${t.priority} |`);
  return [header,...rows].join('\n'); 
}

(async()=>{
  const { data, error } = await supabase.from('maintenance_export_v').select('*').limit(1);
  if(error) throw error; 
  if(!data||!data[0]) throw new Error('No export data');
  
  const { version, tasks } = data[0];
  const banner = `<!-- AUTOGENERATED: Source=maintenance_tasks v${version} (Do not edit by hand) -->`;
  const md = `# Vedlikeholdsoppgaver (versjon ${version})
${banner}

${toTable(tasks)}
`;
  writeFileSync('docs/MAINTENANCE_CHECKLIST.md', md, 'utf8');
  console.log('Wrote docs/MAINTENANCE_CHECKLIST.md');
})();