services:
  api:
    build: .
    environment:
      DATABASE_URL: ${DATABASE_URL:-postgresql+asyncpg://postgres:postgres@localhost:54322/postgres}
      SUPABASE_URL: ${SUPABASE_URL:-https://kkazhcihooovsuwravhs.supabase.co}
      SUPABASE_ANON_KEY: ${SUPABASE_ANON_KEY:-eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtrYXpoY2lob29vdnN1d3JhdmhzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1MzMwMzUsImV4cCI6MjA2MjEwOTAzNX0.-HzjqXYqgThN0PrbrwZlm5GWK1vOGOeYHEEFrt0OpwM}
      SUPABASE_JWKS_URL: ${SUPABASE_JWKS_URL:-https://kkazhcihooovsuwravhs.supabase.co/.well-known/jwks_public}
      CORS_ALLOW_ORIGINS: ${CORS_ALLOW_ORIGINS:-http://localhost:5173,http://localhost:3000}
      API_RATE_LIMIT_PER_MIN: 120
      HMAC_OUTBOUND_SECRET: ${HMAC_OUTBOUND_SECRET:-dev-secret-key}
      ENV: ${ENV:-dev}
    ports: 
      - "8080:8080"
    volumes:
      - ./app:/app/app
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres  
      POSTGRES_PASSWORD: postgres
    ports:
      - "54322:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: