-- Seed maintenance tasks for testing
-- AUTOGENERATED: Source=maintenance_tasks seed data

INSERT INTO maintenance_tasks (title, description, seasons, property_types, frequency_months, priority, estimated_time, cost_estimate, version) VALUES
-- Winter tasks
('Sjekk varmeanlgeg', 'Kontroller at oppvarming fungerer optimalt, rengjør radiatorer og sjekk termostat', ARRAY['Vinter'], ARRAY['Enebolig','Rekkehus','Leilighet','Tomannsbolig','Fritidsbolig'], 12, 'Høy', '2 hours', 1500, '1.0.0'),
('Røykvarslere batteri', 'Bytt batterier i alle røykvarslere og test funksjonalitet', ARRAY['Vinter'], ARRAY['Enebolig','Rekkehus','Leilighet','Tomannsbolig','Fritidsbolig'], 12, 'Høy', '30 minutes', 200, '1.0.0'),
('Isolasjon kontroll', 'Sjekk vinduer og dører for trekk, tett eventuelle hull', ARRAY['Vinter'], ARRAY['Enebolig','Rekkehus','Tomannsbolig','Fritidsbolig'], 12, 'Middels', '3 hours', 800, '1.0.0'),

-- Spring tasks  
('Rengjør takrenner', 'Fjern blader og rusk fra takrenner og nedløpsrør', ARRAY['Vår'], ARRAY['Enebolig','Rekkehus','Tomannsbolig','Fritidsbolig'], 6, 'Høy', '2-3 hours', 500, '1.0.0'),
('Sjekk tak for skader', 'Inspiser takstein/takplater for løse eller ødelagte deler', ARRAY['Vår'], ARRAY['Enebolig','Rekkehus','Tomannsbolig','Fritidsbolig'], 12, 'Høy', '1-2 hours', 0, '1.0.0'),
('Hagearbeid oppstart', 'Klipp plen første gang, plante nye busker/trær hvis nødvendig', ARRAY['Vår'], ARRAY['Enebolig','Rekkehus','Tomannsbolig','Fritidsbolig'], 12, 'Lav', '4-6 hours', 1200, '1.0.0'),

-- Summer tasks
('Vedlikehold terrasse', 'Rengjør og behandle treverk på terrasse/balkong', ARRAY['Sommer'], ARRAY['Enebolig','Rekkehus','Tomannsbolig','Fritidsbolig'], 24, 'Middels', '1 day', 2000, '1.0.0'),
('Sjekk klimaanlegg', 'Rengjør filter og sjekk at klimaanlegg fungerer optimalt', ARRAY['Sommer'], ARRAY['Enebolig','Rekkehus','Leilighet','Tomannsbolig','Fritidsbolig'], 12, 'Middels', '1 hour', 300, '1.0.0'),
('Utvendig maling', 'Inspiser fasade for avskalling, touch-up maling ved behov', ARRAY['Sommer'], ARRAY['Enebolig','Rekkehus','Tomannsbolig'], 36, 'Lav', '2-3 days', 8000, '1.0.0'),

-- Fall tasks
('Rens skorstein', 'Profesjonell rensing av skorstein før fyringssesongen', ARRAY['Høst'], ARRAY['Enebolig','Rekkehus','Tomannsbolig','Fritidsbolig'], 12, 'Høy', '2 hours', 2500, '1.0.0'),
('Vinterforberedelser', 'Tapp vann fra utendørs kraner, sjekk isolasjon på rør', ARRAY['Høst'], ARRAY['Enebolig','Rekkehus','Tomannsbolig','Fritidsbolig'], 12, 'Høy', '2 hours', 500, '1.0.0'),
('Løv og hageopprydding', 'Rake løv, beskytt planter for vinteren', ARRAY['Høst'], ARRAY['Enebolig','Rekkehus','Tomannsbolig','Fritidsbolig'], 12, 'Middels', '3-4 hours', 600, '1.0.0'),

-- Year-round tasks
('Sjekk brannslukningsapparater', 'Test alle brannslukningsapparater og bytt ved behov', ARRAY['Vinter','Vår','Sommer','Høst'], ARRAY['Enebolig','Rekkehus','Leilighet','Tomannsbolig','Fritidsbolig'], 24, 'Høy', '15 minutes', 800, '1.0.0'),
('Hovedstrømbryter test', 'Test at hovedstrømbryter og jordfeilbryter fungerer', ARRAY['Vinter','Vår','Sommer','Høst'], ARRAY['Enebolig','Rekkehus','Leilighet','Tomannsbolig','Fritidsbolig'], 6, 'Høy', '5 minutes', 0, '1.0.0');