openapi: 3.0.3
info:
  title: Homni API
  description: |
    The Homni platform API provides endpoints for lead generation, property documentation, 
    and DIY home selling features. This hybrid platform combines functionality from 
    Bytt.no (lead generation), Boligmappa.no (property documentation), and Propr.no (DIY selling).
  version: 1.0.0
  contact:
    name: Homni Support
    email: support@homni.no
  license:
    name: Proprietary
    
servers:
  - url: https://kkazhcihooovsuwravhs.supabase.co/functions/v1
    description: Production API
  - url: http://localhost:54321/functions/v1
    description: Local development

security:
  - ApiKeyAuth: []
  - BearerAuth: []

paths:
  /health:
    get:
      summary: Health Check
      description: Check the health status of the API and database
      operationId: getHealth
      tags:
        - System
      security: []
      responses:
        '200':
          description: Service is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum: [healthy]
                  timestamp:
                    type: string
                    format: date-time
                  version:
                    type: string
                  database:
                    type: object
                    properties:
                      status:
                        type: string
                        enum: [connected, error]
                      latency_ms:
                        type: number
        '503':
          description: Service is unhealthy
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /leads:
    post:
      summary: Create Lead
      description: Create a new property lead for distribution to qualified buyers
      operationId: createLead
      tags:
        - Leads
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateLeadRequest'
      responses:
        '201':
          description: Lead created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Lead'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: apikey
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Error:
      type: object
      required:
        - error
        - message
      properties:
        error:
          type: string
        message:
          type: string
        details:
          type: object

    CreateLeadRequest:
      type: object
      required:
        - property_type
        - location
        - contact_info
      properties:
        property_type:
          type: string
          enum: [house, apartment, cabin, commercial]
        location:
          type: object
          required:
            - address
            - postal_code
            - city
          properties:
            address:
              type: string
            postal_code:
              type: string
            city:
              type: string
            municipality:
              type: string
        contact_info:
          type: object
          required:
            - name
            - email
          properties:
            name:
              type: string
            email:
              type: string
              format: email
            phone:
              type: string

    Lead:
      type: object
      required:
        - id
        - property_type
        - location
        - status
        - created_at
      properties:
        id:
          type: string
          format: uuid
        property_type:
          type: string
          enum: [house, apartment, cabin, commercial]
        location:
          type: object
        contact_info:
          type: object
        status:
          type: string
          enum: [pending, distributed, closed]
        created_at:
          type: string
          format: date-time

tags:
  - name: System
    description: System health and status endpoints
  - name: Leads
    description: Lead generation and management