// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hiqicllojjemkxdmvuis.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhpcWljbGxvamplbWt4ZG12dWlzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4NTE2MTUsImV4cCI6MjA2MTQyNzYxNX0.5kCyLVQ_KDiGuOPV5n-RTA4p7EJ3KcLbva5HN8rFE_g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);