name: Dependency Health Check

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'package.json'
      - 'package-lock.json'
      - 'tsconfig*.json'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'package.json'
      - 'package-lock.json'
      - 'tsconfig*.json'
  schedule:
    # Run daily at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  dependency-audit:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Run Dev Doctor
      id: devdoctor
      uses: ./.github/actions/dev-doctor
      continue-on-error: true
        
    - name: Install dependencies (with intelligent fallback)
      run: |
        if [ "${{ steps.devdoctor.outputs.has-version-conflicts }}" = "true" ]; then
          echo "⚠️ Version conflicts detected - using --legacy-peer-deps fallback"
          npm ci --legacy-peer-deps
        else
          echo "✅ No conflicts detected - using standard npm ci"
          npm ci
        fi
      
    - name: Run dependency analysis
      run: tsx scripts/clean-dependencies.ts
      
    - name: Validate dependencies
      run: tsx scripts/validate-dependencies.ts
      
    - name: Run dependency verification
      run: tsx dependency-check.ts
      
    - name: Security audit
      run: npm audit --audit-level moderate
      continue-on-error: true
      
    - name: Check for outdated packages
      run: npm outdated
      continue-on-error: true
      
    - name: TypeScript compilation check
      run: npm run typecheck
      
    - name: Create dependency report
      if: always()
      run: |
        echo "# Dependency Health Report" > dependency-report.md
        echo "Generated: $(date)" >> dependency-report.md
        echo "" >> dependency-report.md
        echo "## Package Audit" >> dependency-report.md
        npm audit --json > audit.json || true
        echo "\`\`\`json" >> dependency-report.md
        cat audit.json >> dependency-report.md
        echo "\`\`\`" >> dependency-report.md
        
    - name: Upload dependency report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: dependency-report
        path: dependency-report.md
        retention-days: 30